$(document).ready(function(){
	    $("#show").click(function(){
	        $("#text").hide();
	        $("#showhide").show();
	    });
	});
	$(document).ready(function(){
	    $("#hide").click(function(){
	        $("#text").show();
	        $("#showhide").hide();
	    });
	});